main: com.tavstal.Plugin
name: TemplatePlugin
description: This plugin does so much stuff it can't be contained!
authors: [tavstal]
load: POSTWORLD
version: 1.0
api-version: 1.15
commands:
   template:
      aliases: [temp]
      description: This is a template
      usage: /template
      permission: template.command.template
      permission-message: You do not have permission to use this command.
   getitem:
      description: This is a template
      usage: /getitem
      permission: template.command.getitem
      permission-message: You do not have permission to use this command.